name: Require Members Approval

on:
  pull_request_review:
    types: [editted, submitted]

jobs:
  require_members_approval:
    name: Require Members Approval
    runs-on: ubuntu-latest
    steps:
      - name: Request review based on files changes and/or groups the author belongs to
        uses: creotiv/custom-approval-management@v0.0.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config: .github/main_approval.yml 
